# -*- coding: utf-8 -*-
"""FINAL_ML_Phase2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6D1eGZDDv-Lfj5Jt1-Fq_O0c4K3XO0G

# Machine.learn()

# Main Libraries
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math

"""# Data Exploration"""

from google.colab import drive
drive.mount('/content/drive')

# Abdelrahman Drive
data = pd.read_csv("/content/drive/Shareddrives/ML Project/Copy of train.csv")

df = data.copy()

df

df.shape

df.info()

df.describe()

df = df.rename(columns={'label': 'class'})

df.duplicated().sum()

df = df.dropna(subset=['class'])

feature_cols = [col for col in df.columns if col != 'class']
df = df.drop_duplicates(subset=feature_cols)

df.duplicated().sum()

df.isnull().sum()

df.shape

test_df = pd.read_csv("/content/drive/Shareddrives/ML Project/Copy of test.csv")

X_test = test_df.drop(columns=['Id'])
test_ids = test_df['Id']

X_test

"""# Data Preprocessing"""

X_test.drop(columns=['src_rate', 'dst_rate'], inplace=True)

df = df.drop(columns = ['src_rate', 'dst_rate'])
df.info()

x = df.drop(columns = ['class'])
y = df['class']

from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()
y_label_encoded = label.fit_transform(y.astype(str))
y_label_encoded = pd.Series(label.fit_transform(y.astype(str)), index=y.index, name=y.name)
y_label_encoded

y_label_encoded.value_counts()

def full_feature_engineering_MORE(df):
    df = df.copy()

    # Basic Ratios
    df['header_per_time'] = df['header_size'] / (df['flow_time'] + 1e-6)
    df['packet_per_rate'] = df['packet_duration'] / (df['overall_rate'] + 1e-6)
    df['header_per_packet'] = df['header_size'] / (df['packet_duration'] + 1e-6)
    df['packet_per_time'] = df['packet_duration'] / (df['flow_time'] + 1e-6)
    df['rate_per_header'] = df['overall_rate'] / (df['header_size'] + 1e-6)
    df['max_per_cov'] = df['max_value'] / (df['value_covariance'] + 1e-6)

    # Flags
    flag_cols = ['fin_flags', 'syn_flags', 'rst_flags', 'psh_flags', 'ack_flags']
    df['total_flags'] = df[flag_cols].sum(axis=1)
    df['fin_ratio'] = df['fin_flags'] / (df['total_flags'] + 1e-6)
    df['flags_ratio'] = df['syn_flags'] / (df['ack_flags'] + 1e-6)
    df['is_syn_ack'] = ((df['syn_flags'] > 0) & (df['ack_flags'] > 0)).astype(int)

    # Protocols
    protocol_cols = ['protocol_http', 'protocol_https', 'protocol_tcp', 'protocol_udp', 'protocol_icmp']
    df['protocol_count'] = df[protocol_cols].sum(axis=1)
    df['tcp_udp_ratio'] = (df['protocol_tcp'] + 1e-6) / (df['protocol_udp'] + 1e-6)
    df['http_https_ratio'] = (df['protocol_http'] + 1e-6) / (df['protocol_https'] + 1e-6)

    # Interactions
    df['flow_rate_interaction'] = df['flow_time'] * df['overall_rate']
    df['header_max_interaction'] = df['header_size'] * df['max_value']
    df['flow_max_interact'] = df['flow_time'] * df['max_value']
    df['header_cov_interact'] = df['header_size'] * df['value_covariance']
    df['packet_time_interact'] = df['packet_duration'] * df['flow_time']
    df['rate_sq'] = df['overall_rate'] ** 2

    # Transforms
    for col in ['flow_time', 'header_size', 'packet_duration', 'overall_rate', 'max_value', 'value_covariance']:
        df[f'log_{col}'] = np.log1p(df[col])
        df[f'sqrt_{col}'] = np.sqrt(df[col])


    # Flag Interactions
    df['syn_fin_combo'] = df['syn_flags'] * df['fin_flags']
    df['ack_psh_combo'] = df['ack_flags'] * df['psh_flags']

    # Protocol + Flag Interaction
    df['tcp_fin_ack'] = df['protocol_tcp'] * df['fin_flags'] * df['ack_flags']

    # Binned Indicators (Binary flags for outliers)
    df['is_long_flow'] = (df['flow_time'] > df['flow_time'].median()).astype(int)
    df['is_high_rate'] = (df['overall_rate'] > df['overall_rate'].quantile(0.75)).astype(int)

    # More Flags
    df['syn_to_ack_ratio'] = df['syn_flags'] / (df['ack_flags'] + 1)
    df['fin_to_rst_ratio'] = df['fin_flags'] / (df['rst_flags'] + 1)
    df['ack_psh_to_total_ratio'] = (df['ack_flags'] + df['psh_flags']) / (df['total_flags'] + 1)

    # Attack separators for Better Recon, DoS, Mirai Detection
    df['rst_ratio'] = df['rst_flags'] / (df['total_flags'] + 1e-6)
    df['icmp_ratio'] = df['protocol_icmp'] / (df['protocol_count'] + 1e-6)
    df['is_small_packet'] = (df['header_size'] < df['header_size'].quantile(0.25)).astype(int)
    df['is_syn_no_ack'] = ((df['syn_flags'] > 0) & (df['ack_flags'] == 0)).astype(int)

    return df

x = full_feature_engineering_MORE(x)
X_test = full_feature_engineering_MORE(X_test)

x.info()

"""* **Try with and without**"""

from sklearn.metrics import accuracy_score
from google.colab import files

X_resampled_df = x.copy()
y_resampled_series = y_label_encoded.copy()

y_label_encoded.shape

train_data = pd.concat([X_resampled_df, y_resampled_series], axis=1)

feature_cols = [col for col in train_data.columns if col != 'class']
train_data = train_data.drop_duplicates(subset=feature_cols)

train_data['class'].isna().sum()

y_label_encoded = train_data['class']
y_label_encoded.isna().sum()

train_data = train_data.dropna(subset=['class'])

train_data['class'].isna().sum()

train_data.duplicated().sum()

# Drop duplicate rows based on features only
train_data_clean = train_data.drop_duplicates(subset=x.columns, keep='first')
train_data = train_data.dropna(inplace=True)

X_processed_dropped = train_data_clean.drop(columns = ['class'])
y_label_encoded = train_data_clean['class']

X_processed_dropped.duplicated().sum()

X_processed_dropped.isna().sum()

X_processed_dropped.shape

y_label_encoded.shape

y_label_encoded.isna().sum()

# Reset index
X_processed_dropped = X_processed_dropped.reset_index(drop=True)
y_label_encoded = y_label_encoded.reset_index(drop=True)

# Check shapes
print(f"Before cleaning: X shape = {X_processed_dropped.shape}, y shape = {y_label_encoded.shape}")

# Remove rows where target is NaN
non_nan_mask = y_label_encoded.notna()
X_processed_clean = X_processed_dropped.loc[non_nan_mask].reset_index(drop=True)
y_clean = y_label_encoded.loc[non_nan_mask].reset_index(drop=True)

print(f"After dropping NaN targets: X shape = {X_processed_clean.shape}, y shape = {y_clean.shape}")

# Drop rows with NaNs in features
nan_rows = X_processed_clean.isna().any(axis=1)
print(f"Rows with NaNs in features: {nan_rows.sum()}")

X_processed_clean = X_processed_clean.loc[~nan_rows].reset_index(drop=True)
y_clean = y_clean.loc[~nan_rows].reset_index(drop=True)

print(f"After dropping feature NaNs: X shape = {X_processed_clean.shape}, y shape = {y_clean.shape}")

# Drop duplicates
combined = pd.concat([X_processed_clean, y_clean], axis=1)
before_dupes = combined.shape[0]

combined_clean = combined.drop_duplicates()
after_dupes = combined_clean.shape[0]

print(f"Removed {before_dupes - after_dupes} duplicate rows")

# Split back to X and y
X_final = combined_clean.drop(columns=[y_clean.name]).reset_index(drop=True)
y_final = combined_clean[y_clean.name].reset_index(drop=True)

print(f"\n Final Clean Data: X shape = {X_final.shape}, y shape = {y_final.shape}")

y_train = y_final.copy()
X_train = X_final.copy()

X_test = X_test[X_train.columns]

"""# Model Training and Test Predictions Submission

# XGBoost
"""

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
import xgboost as xgb
from google.colab import files

print(xgb.__version__)

# Setup
n_splits = 5
cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
n_classes = len(np.unique(y_train))
n_features = X_train.shape[1]

# XGBoost Params
xgb_params = {
    'max_depth': 10,
    'learning_rate': 0.025,
    'subsample': 0.7,
    'colsample_bytree': 0.7,
    'objective': 'multi:softprob',
    'num_class': n_classes,
    'random_state': 42,
    'reg_alpha': 2,
    'reg_lambda': 2,
    'tree_method': 'hist',
    'eval_metric': ['mlogloss', 'merror']
}

# Cross-validated Training
xgb_oof_preds = np.zeros((X_train.shape[0], n_classes))

for fold, (train_idx, val_idx) in enumerate(cv.split(X_train, y_train)):
    print(f"\nFold {fold + 1}/{n_splits}")

    dtrain = xgb.DMatrix(X_train.iloc[train_idx], label=y_train.iloc[train_idx])
    dval = xgb.DMatrix(X_train.iloc[val_idx], label=y_train.iloc[val_idx])

    evals = [(dtrain, 'train'), (dval, 'eval')]

    model = xgb.train(
        params=xgb_params,
        dtrain=dtrain,
        num_boost_round=800, # EXTRA
        evals=evals,
        early_stopping_rounds=20,
        verbose_eval=10
    )

    xgb_oof_preds[val_idx] = model.predict(dval)

# CV Score
xgb_cv_score = accuracy_score(y_train, np.argmax(xgb_oof_preds, axis=1))
print(f"\n XGBoost CV Accuracy: {xgb_cv_score:.4f}")

# Train final model on FULL data
dtrain_full = xgb.DMatrix(X_train, label=y_train)
final_model = xgb.train(
    params=xgb_params,
    dtrain=dtrain_full,
    num_boost_round=int(model.best_iteration + 1)
)

# Predict on Test Set
dtest = xgb.DMatrix(X_test)
test_preds = np.argmax(final_model.predict(dtest), axis=1)

# Inverse transform labels if using LabelEncoder
test_preds_original = label.inverse_transform(test_preds)

# Save Submission
submission_counter = 2
submission = pd.DataFrame({'Id': test_ids, 'target': test_preds_original})
filename = f'submission_{submission_counter}_XGBoost_best_alladd_f.csv'
submission.to_csv(filename, index=False)
files.download(filename)

print(f"Saved submission: {filename}")

# Train Accuracy on FULL Data
train_preds = np.argmax(final_model.predict(dtrain_full), axis=1)
train_acc = accuracy_score(y_train, train_preds)
print(f"✅ Train accuracy (full data): {train_acc:.4f}")

# Get feature importances using get_score()
score_dict = final_model.get_score(importance_type='weight')

# Convert dict to Series
feature_importance = pd.Series(score_dict)

# Match order with X_train columns (some features may have zero importance)
feature_importance = feature_importance.reindex(X_train.columns, fill_value=0)

# Sort
feature_importance = feature_importance.sort_values(ascending=False)

print(f"Features Ranked by Importance:")
print(feature_importance)

# Plot ALL features
plt.figure(figsize=(max(12, len(feature_importance) * 0.5), 6))
plt.title("XGBoost Feature Importances (All Features)")

bars = plt.bar(range(len(feature_importance)), feature_importance.values, align="center", color='skyblue')
plt.xticks(range(len(feature_importance)), feature_importance.index, rotation=90)

# Add text labels above bars
for bar, value in zip(bars, feature_importance.values):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f'{int(value)}', ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.show()

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
    average_precision_score,
    f1_score,
    log_loss
)
from sklearn.preprocessing import label_binarize

# Get class names from LabelEncoder
class_names = label.classes_

print("Evaluating Final Model on Full Train Set")

y_true = y_train
y_pred = train_preds
y_pred_proba = final_model.predict(dtrain_full)
y_true_names = label.inverse_transform(y_true)
y_pred_names = label.inverse_transform(y_pred)

# Classification Report
print("Classification Report:")
print(classification_report(y_true_names, y_pred_names, target_names=class_names))

# Confusion Matrix
plt.figure(figsize=(10, 8))
cm = confusion_matrix(y_true_names, y_pred_names, labels=class_names)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title("Confusion Matrix - Full Train")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ROC AUC & Precision-Recall
y_true_bin = label_binarize(y_true, classes=range(n_classes))

# ROC Curves
plt.figure(figsize=(12, 8))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_proba[:, i])
    auc = roc_auc_score(y_true_bin[:, i], y_pred_proba[:, i])
    plt.plot(fpr, tpr, label=f"{class_names[i]} AUC: {auc:.2f}")
plt.plot([0, 1], [0, 1], 'k--')
plt.title("ROC Curves - Final Model")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.legend()
plt.grid()
plt.show()

# Precision-Recall Curves
plt.figure(figsize=(12, 8))
for i in range(n_classes):
    precision, recall, _ = precision_recall_curve(y_true_bin[:, i], y_pred_proba[:, i])
    ap = average_precision_score(y_true_bin[:, i], y_pred_proba[:, i])
    plt.plot(recall, precision, label=f"{class_names[i]} AP: {ap:.2f}")
plt.title("Precision-Recall Curves - Final Model")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.legend()
plt.grid()
plt.show()